[tool.poetry]
name = "backend-with-pypi"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = ">=3.8"
hatchling = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
